"""Tests for the scalar field class."""
import pytest

import fridom.framework as fr

# ================================================================
#  Fixtures
# ================================================================



# ================================================================
#  Tests
# ================================================================

def test_init(): ...

def test_get_attr(): ...

def test_set_attr(): ...

# ----------------------------------------------------------------
#  Test general methods
# ----------------------------------------------------------------

def test_fft(): ...

def test_ifft(): ...

def test_sync(): ...

def test_apply_watermask(): ...

def test_has_nan(): ...

def test_copy(): ...

def test_unpad(): ...

def test_get_mesh(): ...

def test_interpolate(): ...

# ----------------------------------------------------------------
#  Test differential operators
# ----------------------------------------------------------------

def test_diff(): ...

def test_grad(): ...

def test_laplacian(): ...

def test_div(): ...

# ----------------------------------------------------------------
#  Test xarray interface
# ----------------------------------------------------------------

def test_xr(): ...

def test_xrs(): ...

def test_from_xr(): ...

def test_netcdf_save_load(): ...

# ----------------------------------------------------------------
#  Test slicing methods
# ----------------------------------------------------------------

def test_getitem(): ...

def test_setitem(): ...

# ----------------------------------------------------------------
#  Pickling
# ----------------------------------------------------------------

def test_pickle(): ...

# ----------------------------------------------------------------
#  Test arithmetic operations
# ----------------------------------------------------------------

def test_apply_operator(): ...

def test_abs(): ...

def test_sum(): ...

def test_max(): ...

def test_min(): ...

def test_integrate(): ...

def test_norm_l2(): ...

def test_dot(): ...

def test_conj(): ...
